// The doors page in the site's seven languages.

export const PANEL_TEXTS = {
  pl: {
    pageTitle: 'Dla organizatorów — blindtennis.app', language: 'Język', otherPages: 'Inne strony',
    title: 'Dla organizatorów',
    lead: 'Logowanie dla osób, które prowadzą turnieje na blindtennis.app.',
    officeName: 'Biuro turnieju',
    officeText: 'Dzień turnieju: zawodnicy, losowanie, plan meczów, grupy, drabinka i wyniki.',
    officeHow: 'Logujesz się hasłem biura, które daje organizator turnieju.',
    organizerName: 'Panel organizatora serii',
    organizerText: 'Dla serii turniejów: zakładanie turniejów, zgłoszenia, korty, logo i wyniki serii.',
    organizerHow: 'Logujesz się adresem e-mail i hasłem ustawionym z zaproszenia.',
    contactAsk: 'Chcesz poprowadzić turniej albo serię na blindtennis.app? Napisz:',
    backToScores: 'Wróć do wyników', privacy: 'Polityka prywatności',
  },
  en: {
    pageTitle: 'For organizers — blindtennis.app', language: 'Language', otherPages: 'Other pages',
    title: 'For organizers',
    lead: 'Sign-in for the people who run tournaments on blindtennis.app.',
    officeName: 'Tournament office',
    officeText: 'Tournament day: players, the draw, the match schedule, groups, the bracket and results.',
    officeHow: 'You sign in with the office password from the tournament’s organizer.',
    organizerName: 'Series organizer panel',
    organizerText: 'For a tournament series: creating tournaments, entries, courts, logos and the series’ results.',
    organizerHow: 'You sign in with your e-mail address and the password set from your invitation.',
    contactAsk: 'Want to run a tournament or a series on blindtennis.app? Write to',
    backToScores: 'Back to scores', privacy: 'Privacy policy',
  },
  de: {
    pageTitle: 'Für Veranstalter — blindtennis.app', language: 'Sprache', otherPages: 'Weitere Seiten',
    title: 'Für Veranstalter',
    lead: 'Anmeldung für alle, die Turniere auf blindtennis.app ausrichten.',
    officeName: 'Turnierbüro',
    officeText: 'Der Turniertag: Spieler, Auslosung, Spielplan, Gruppen, Turnierbaum und Ergebnisse.',
    officeHow: 'Sie melden sich mit dem Büropasswort an, das Sie vom Veranstalter bekommen.',
    organizerName: 'Veranstalterbereich der Serie',
    organizerText: 'Für eine Turnierserie: Turniere anlegen, Meldungen, Plätze, Logos und Ergebnisse der Serie.',
    organizerHow: 'Sie melden sich mit Ihrer E-Mail-Adresse und dem Passwort aus Ihrer Einladung an.',
    contactAsk: 'Sie möchten ein Turnier oder eine Serie auf blindtennis.app ausrichten? Schreiben Sie an',
    backToScores: 'Zurück zu den Ergebnissen', privacy: 'Datenschutzerklärung',
  },
  it: {
    pageTitle: 'Per gli organizzatori — blindtennis.app', language: 'Lingua', otherPages: 'Altre pagine',
    title: 'Per gli organizzatori',
    lead: 'Accesso per chi gestisce tornei su blindtennis.app.',
    officeName: 'Ufficio del torneo',
    officeText: 'Il giorno del torneo: giocatori, sorteggio, programma, gironi, tabellone e risultati.',
    officeHow: 'Accedi con la password dell’ufficio data dall’organizzatore del torneo.',
    organizerName: 'Area organizzatori della serie',
    organizerText: 'Per una serie di tornei: creare tornei, iscrizioni, campi, loghi e risultati della serie.',
    organizerHow: 'Accedi con il tuo indirizzo e-mail e la password impostata dall’invito.',
    contactAsk: 'Vuoi gestire un torneo o una serie su blindtennis.app? Scrivi a',
    backToScores: 'Torna ai risultati', privacy: 'Informativa sulla privacy',
  },
  es: {
    pageTitle: 'Para organizadores — blindtennis.app', language: 'Idioma', otherPages: 'Otras páginas',
    title: 'Para organizadores',
    lead: 'Acceso para quienes organizan torneos en blindtennis.app.',
    officeName: 'Oficina del torneo',
    officeText: 'El día del torneo: jugadores, sorteo, calendario, grupos, cuadro y resultados.',
    officeHow: 'Entras con la contraseña de la oficina que te da el organizador del torneo.',
    organizerName: 'Panel de organizador de la serie',
    organizerText: 'Para una serie de torneos: crear torneos, inscripciones, pistas, logos y resultados de la serie.',
    organizerHow: 'Entras con tu correo y la contraseña que estableciste desde la invitación.',
    contactAsk: '¿Quieres organizar un torneo o una serie en blindtennis.app? Escribe a',
    backToScores: 'Volver a los resultados', privacy: 'Política de privacidad',
  },
  fr: {
    pageTitle: 'Pour les organisateurs — blindtennis.app', language: 'Langue', otherPages: 'Autres pages',
    title: 'Pour les organisateurs',
    lead: 'Connexion pour les personnes qui organisent des tournois sur blindtennis.app.',
    officeName: 'Bureau du tournoi',
    officeText: 'Le jour du tournoi : joueurs, tirage, programme, poules, tableau et résultats.',
    officeHow: 'Vous vous connectez avec le mot de passe du bureau donné par l’organisateur du tournoi.',
    organizerName: 'Espace organisateur de la série',
    organizerText: 'Pour une série de tournois : créer des tournois, inscriptions, courts, logos et résultats de la série.',
    organizerHow: 'Vous vous connectez avec votre adresse e-mail et le mot de passe défini depuis l’invitation.',
    contactAsk: 'Vous voulez organiser un tournoi ou une série sur blindtennis.app ? Écrivez à',
    backToScores: 'Retour aux scores', privacy: 'Politique de confidentialité',
  },
  lt: {
    pageTitle: 'Organizatoriams — blindtennis.app', language: 'Kalba', otherPages: 'Kiti puslapiai',
    title: 'Organizatoriams',
    lead: 'Prisijungimas tiems, kas organizuoja turnyrus blindtennis.app.',
    officeName: 'Turnyro biuras',
    officeText: 'Turnyro diena: žaidėjai, burtai, rungtynių planas, grupės, lentelė ir rezultatai.',
    officeHow: 'Prisijungiate biuro slaptažodžiu, kurį duoda turnyro organizatorius.',
    organizerName: 'Serijos organizatoriaus skydelis',
    organizerText: 'Turnyrų serijai: turnyrų kūrimas, registracijos, aikštelės, logotipai ir serijos rezultatai.',
    organizerHow: 'Prisijungiate el. paštu ir slaptažodžiu, nustatytu iš kvietimo.',
    contactAsk: 'Norite organizuoti turnyrą ar seriją blindtennis.app? Rašykite',
    backToScores: 'Grįžti į rezultatus', privacy: 'Privatumo politika',
  },
};
