"""Database access layer for v2 (package facade)."""
from __future__ import annotations

from . import brackets, categories, connection, courts, history, players, schedule, teams, tournaments

from .connection import (
    _default_simulation_office_password_hash,
    db_conn,
    init_db,
    fetch_app_settings,
    upsert_app_settings,
    _utc_now,
)

from .courts import (
    fetch_courts,
    fetch_courts_for_tournament,
    fetch_court,
    get_tournament_id_for_court,
    insert_court,
    upsert_court,
    delete_court,
    rename_court,
    create_tournament_courts,
    sync_tournament_courts,
)

from .tournaments import (
    get_active_tournament_id,
    get_active_tournament_name,
    fetch_active_tournaments,
    fetch_tournaments,
    fetch_tournament,
    insert_tournament,
    update_tournament,
    mark_tournament_summary_sent,
    delete_tournament,
    set_active_tournament,
    set_tournament_active_state,
    _tournament_quick_info_key,
    get_tournament_quick_info,
    save_tournament_quick_info,
    get_public_tournament_quick_info,
)

from .players import (
    _normalize_player_name,
    _player_surname,
    fetch_players,
    fetch_active_tournament_players,
    fetch_players_for_active_tournaments,
    _tournament_links_global_players,
    _ensure_global_player,
    insert_player,
    _sync_player_name_across_tournament,
    update_player,
    delete_player,
    bulk_insert_players,
)

from .schedule import (
    DEFAULT_GROUP_SCHEDULE_NOTE_PL,
    DEFAULT_KNOCKOUT_SCHEDULE_NOTE_PL,
    DEFAULT_GROUP_SCHEDULE_NOTE_DE,
    DEFAULT_KNOCKOUT_SCHEDULE_NOTE_DE,
    _tournament_country_code,
    _default_group_schedule_note,
    _default_knockout_schedule_note,
    ensure_group_rematch_schedule_entries,
    _schedule_day_for_tournament,
    _knockout_schedule_day_for_tournament,
    _autoschedule_phases_include_knockout,
    _schedule_pair_clause,
    _schedule_entry_is_assigned,
    _schedule_entry_is_unplaced,
    _schedule_entry_priority,
    _prune_duplicate_schedule_entries,
    _format_score_text,
    _schedule_match_result,
    _schedule_row_payload,
    fetch_tournament_schedule,
    _parse_schedule_reference_datetime,
    find_suggested_schedule_match,
    build_public_schedule_payload,
    _coerce_schedule_entry,
    upsert_tournament_schedule_entries,
    update_tournament_schedule_entry,
    delete_tournament_schedule_entry,
    publish_tournament_schedule,
    _insert_group_round_robin_schedule_entries,
    ensure_group_schedule_entries,
    ensure_knockout_schedule_entries,
    link_schedule_to_match,
    unlink_schedule_from_match,
    _autoscheduler_settings_key,
    get_autoscheduler_config,
    save_autoscheduler_config,
    _schedule_entry_match_dict,
    generate_autoschedule_proposal,
    apply_autoschedule_placements,
    move_schedule_entry_with_cascade,
    unassign_schedule_entry,
    delete_unassigned_schedule_entries,
)

from .brackets import (
    _bracket_row_match_priority,
    _find_bracket_groups_for_player,
    detect_bracket_context,
    _split_bracket_label,
    GROUP_PHASE,
    GROUP_REMATCH_PHASE,
    _GROUP_REMATCH_PHASE_MARKERS,
    normalize_group_stage_phase,
    is_group_stage_phase,
    is_knockout_stage_phase,
    expected_group_matches_count,
    count_finished_group_matches,
    _phase_kind,
    _group_sort_key,
    _is_group_partition_name,
    _knockout_bucket_key,
    _is_knockout_placeholder_name,
    _standing_placeholder,
    _is_group_play_complete,
    _bucket_groups_play_complete,
    _slot_phase_matches,
    _expected_group_matches_count,
    _count_finished_group_matches,
    _assign_knockout_slot_player,
    _knockout_schedule_player_names,
    _build_knockout_slots_for_category,
    _build_single_group_final_slots,
    _build_provisional_single_group_final_slots,
    _build_provisional_four_player_group_knockout_slots,
    _build_provisional_knockout_slots_for_category,
    _compute_provisional_knockout_slots_from_bracket,
    seed_knockout_rematch_for_groups,
    _build_four_player_group_knockout_slots,
    _compute_knockout_slots_from_bracket,
    seed_provisional_knockout_from_groups,
    _merge_bracket_knockout_slots,
    maybe_generate_knockout_from_completed_groups,
    advance_knockout,
    _advance_to_next_round,
    save_bracket_groups,
    fetch_bracket_groups,
    _find_group_matches,
    _is_stb,
    _is_empty_set,
    _build_set_detail,
    _format_set_score,
    _compute_standings,
    save_bracket_knockout,
    fetch_bracket_knockout,
    _detect_knockout_result,
    get_full_bracket,
    generate_knockout_from_standings,
)

from .categories import (
    _tournament_category_counts,
    fetch_tournament_categories,
    fetch_tournament_category,
    _insert_tournament_category_row,
    confirm_tournament_categories,
    insert_tournament_category,
    _propagate_tournament_category_label,
    update_tournament_category,
    delete_tournament_category,
    migrate_tournament_categories_from_legacy,
    _mixed_categories_settings_key,
    get_mixed_categories,
    get_planning_mixed_bands,
    clear_legacy_mixed_categories,
    set_mixed_categories,
)

from .teams import (
    TeamConflictError,
    TeamValidationError,
    fetch_tournament_teams,
    fetch_tournament_team,
    insert_tournament_team,
    delete_tournament_team,
)

from .history import (
    insert_match_history,
    delete_latest_history_entry,
    fetch_match_history,
    _resolve_name,
)

# Wire cross-module globals (move-only bodies keep bare names).
_MODULES = {
    'connection': connection,
    'courts': courts,
    'tournaments': tournaments,
    'players': players,
    'schedule': schedule,
    'brackets': brackets,
    'categories': categories,
    'history': history,
    'teams': teams,
}
_INJECTIONS = {
    'schedule': {
        'GROUP_PHASE': 'brackets',
        'GROUP_REMATCH_PHASE': 'brackets',
        '_knockout_schedule_player_names': 'brackets',
        '_split_bracket_label': 'brackets',
        'fetch_bracket_groups': 'brackets',
        'fetch_courts_for_tournament': 'courts',
        'fetch_tournament': 'tournaments',
        'seed_provisional_knockout_from_groups': 'brackets',
    },
    'brackets': {
        '_normalize_player_name': 'players',
        '_player_surname': 'players',
        'ensure_group_rematch_schedule_entries': 'schedule',
        'ensure_group_schedule_entries': 'schedule',
        'ensure_knockout_schedule_entries': 'schedule',
    },
    'categories': {
        'fetch_bracket_groups': 'brackets',
    },
}
for _consumer, _mapping in _INJECTIONS.items():
    _mod = _MODULES[_consumer]
    for _sym, _owner in _mapping.items():
        setattr(_mod, _sym, getattr(_MODULES[_owner], _sym))

__all__ = [
    '_default_simulation_office_password_hash',
    'db_conn',
    'init_db',
    'fetch_app_settings',
    'upsert_app_settings',
    '_utc_now',
    'fetch_courts',
    'fetch_courts_for_tournament',
    'fetch_court',
    'get_tournament_id_for_court',
    'insert_court',
    'upsert_court',
    'delete_court',
    'rename_court',
    'create_tournament_courts',
    'sync_tournament_courts',
    'get_active_tournament_id',
    'get_active_tournament_name',
    'fetch_active_tournaments',
    'fetch_tournaments',
    'fetch_tournament',
    'insert_tournament',
    'update_tournament',
    'mark_tournament_summary_sent',
    'delete_tournament',
    'set_active_tournament',
    'set_tournament_active_state',
    '_tournament_quick_info_key',
    'get_tournament_quick_info',
    'save_tournament_quick_info',
    'get_public_tournament_quick_info',
    '_normalize_player_name',
    '_player_surname',
    'fetch_players',
    'fetch_active_tournament_players',
    'fetch_players_for_active_tournaments',
    '_tournament_links_global_players',
    '_ensure_global_player',
    'insert_player',
    '_sync_player_name_across_tournament',
    'update_player',
    'delete_player',
    'bulk_insert_players',
    'DEFAULT_GROUP_SCHEDULE_NOTE_PL',
    'DEFAULT_KNOCKOUT_SCHEDULE_NOTE_PL',
    'DEFAULT_GROUP_SCHEDULE_NOTE_DE',
    'DEFAULT_KNOCKOUT_SCHEDULE_NOTE_DE',
    '_tournament_country_code',
    '_default_group_schedule_note',
    '_default_knockout_schedule_note',
    'ensure_group_rematch_schedule_entries',
    '_schedule_day_for_tournament',
    '_knockout_schedule_day_for_tournament',
    '_autoschedule_phases_include_knockout',
    '_schedule_pair_clause',
    '_schedule_entry_is_assigned',
    '_schedule_entry_is_unplaced',
    '_schedule_entry_priority',
    '_prune_duplicate_schedule_entries',
    '_format_score_text',
    '_schedule_match_result',
    '_schedule_row_payload',
    'fetch_tournament_schedule',
    '_parse_schedule_reference_datetime',
    'find_suggested_schedule_match',
    'build_public_schedule_payload',
    '_coerce_schedule_entry',
    'upsert_tournament_schedule_entries',
    'update_tournament_schedule_entry',
    'delete_tournament_schedule_entry',
    'publish_tournament_schedule',
    '_insert_group_round_robin_schedule_entries',
    'ensure_group_schedule_entries',
    'ensure_knockout_schedule_entries',
    'link_schedule_to_match',
    'unlink_schedule_from_match',
    '_autoscheduler_settings_key',
    'get_autoscheduler_config',
    'save_autoscheduler_config',
    '_schedule_entry_match_dict',
    'generate_autoschedule_proposal',
    'apply_autoschedule_placements',
    'move_schedule_entry_with_cascade',
    'unassign_schedule_entry',
    'delete_unassigned_schedule_entries',
    '_bracket_row_match_priority',
    '_find_bracket_groups_for_player',
    'detect_bracket_context',
    '_split_bracket_label',
    'GROUP_PHASE',
    'GROUP_REMATCH_PHASE',
    '_GROUP_REMATCH_PHASE_MARKERS',
    'normalize_group_stage_phase',
    'is_group_stage_phase',
    'is_knockout_stage_phase',
    'expected_group_matches_count',
    'count_finished_group_matches',
    '_phase_kind',
    '_group_sort_key',
    '_is_group_partition_name',
    '_knockout_bucket_key',
    '_is_knockout_placeholder_name',
    '_standing_placeholder',
    '_is_group_play_complete',
    '_bucket_groups_play_complete',
    '_slot_phase_matches',
    '_expected_group_matches_count',
    '_count_finished_group_matches',
    '_assign_knockout_slot_player',
    '_knockout_schedule_player_names',
    '_build_knockout_slots_for_category',
    '_build_single_group_final_slots',
    '_build_provisional_single_group_final_slots',
    '_build_provisional_four_player_group_knockout_slots',
    '_build_provisional_knockout_slots_for_category',
    '_compute_provisional_knockout_slots_from_bracket',
    'seed_knockout_rematch_for_groups',
    '_build_four_player_group_knockout_slots',
    '_compute_knockout_slots_from_bracket',
    'seed_provisional_knockout_from_groups',
    '_merge_bracket_knockout_slots',
    'maybe_generate_knockout_from_completed_groups',
    'advance_knockout',
    '_advance_to_next_round',
    'save_bracket_groups',
    'fetch_bracket_groups',
    '_find_group_matches',
    '_is_stb',
    '_is_empty_set',
    '_build_set_detail',
    '_format_set_score',
    '_compute_standings',
    'save_bracket_knockout',
    'fetch_bracket_knockout',
    '_detect_knockout_result',
    'get_full_bracket',
    'generate_knockout_from_standings',
    '_tournament_category_counts',
    'fetch_tournament_categories',
    'fetch_tournament_category',
    '_insert_tournament_category_row',
    'confirm_tournament_categories',
    'insert_tournament_category',
    '_propagate_tournament_category_label',
    'update_tournament_category',
    'delete_tournament_category',
    'migrate_tournament_categories_from_legacy',
    '_mixed_categories_settings_key',
    'get_mixed_categories',
    'get_planning_mixed_bands',
    'clear_legacy_mixed_categories',
    'set_mixed_categories',
    'TeamConflictError',
    'TeamValidationError',
    'fetch_tournament_teams',
    'fetch_tournament_team',
    'insert_tournament_team',
    'delete_tournament_team',
    'insert_match_history',
    'delete_latest_history_entry',
    'fetch_match_history',
    '_resolve_name',
]
